language: python
python:
  - "2.6"
  - "2.7"
  - "nightly"
# command to install dependencies
install:
  - pip install paramiko
# command to run tests
script:
  - python startupsystem.py # or py.test for Python versions 3.5 and below